<head>
    <style>
    </style>
</head>
@extends('layout')
@section('content')
{{View::make('sectionMotivate')}}
{{View::make('sectionAbout')}}
{{View::make('sectionServices')}}
{{View::make('sectionHow')}}
{{View::make('sectionEvents')}}
{{View::make('sectionContact')}}
{{View::make('sectionFounder')}}
@endsection